import Foundation

public enum ComposeError: LocalizedError, Sendable {
    case fileNotFound(String)
    case readFailed(String, underlying: Error)
    case parseFailed(String, underlying: Error)
    case noServices
    case missingImage(service: String)
    case buildContextNotFound(path: String, service: String)
    case buildDockerfileNotFound(path: String, service: String)
    case buildFailed(service: String, underlying: Error)
    case invalidField(String, reason: String)
    case unsupportedPort(String)
    case unsupportedVolume(String)
    case unsupportedVolumeOption(String)
    case unsupportedExternalVolume(name: String)
    case undefinedVolume(service: String, volume: String)
    case invalidVolumeName(volume: String, runtimeName: String)
    case includeVolumeConflict(name: String, includePath: String, definedIn: String)
    case volumeCreateFailed(volume: String, underlying: Error)
    case volumeHostPathNotFound(path: String)
    case serviceFailed(service: String, underlying: Error)
    case multipleServiceFailures([(service: String, error: Error)])
    case unknownDependency(service: String, dependency: String)
    case profileExcludedDependency(service: String, dependency: String, requiredProfiles: [String])
    case profileFilterRequiresComposeFile
    case circularDependency(services: [String])
    case circularInclude(chain: [String])
    case includeConflict(service: String, includePath: String, definedIn: String)
    case invalidInclude(reason: String)
    case unresolvedVariable(name: String, composePath: String)
    case rollbackFailed(started: [String], failures: [(container: String, error: Error)])
    case invalidProjectName(String)
    case invalidComposeFilePath(String)
    case undefinedService(service: String)
    case serviceNotFound(service: String, project: String)
    case containerNotFound(container: String)
    case serviceNotRunning(service: String, state: String)
    case ambiguousService(service: String, containers: [String])
    case containerProjectMismatch(container: String, project: String)
    case invalidScaleSpec(String)
    case replicasBelowMinimum(service: String, count: Int)
    case containerNameNotSupportedWithReplicas(service: String, containerName: String)
    case staticPortBlocksScaling(service: String, port: String, replicas: Int)
    case scaleServiceRequiresProfile(service: String, requiredProfiles: [String])
    case healthCheckTimeout(dependency: String, container: String)
    case serviceStartTimeout(dependency: String, container: String)
    case serviceCompletedUnsuccessfully(dependency: String, container: String, exitCode: Int32)
    case serviceCompletionNeverAppeared(dependency: String, container: String)
    case serviceCompletionExitTimeout(dependency: String, container: String)
    case unsupportedExternalResource(kind: ComposeFileMountKind)
    case undefinedResource(name: String, kind: ComposeFileMountKind)
    case resourceFileNotFound(path: String, kind: ComposeFileMountKind)
    case includeResourceConflict(name: String, kind: ComposeFileMountKind, includePath: String, definedIn: String)
    case unsupportedExternalNetwork(name: String)
    case unsupportedNetworkOption(network: String, option: String)
    case undefinedNetwork(service: String, network: String)
    case invalidNetworkName(network: String, runtimeName: String)
    case includeNetworkConflict(name: String, includePath: String, definedIn: String)
    case networkCreateFailed(network: String, underlying: Error)
    case networksRequireMacOS26
    case invalidCpPath(reason: String)
    case cpHostPathOutsideCWD(path: String)
    case cpSourceNotFound(path: String)
    case cpContainerToContainer
    case cpLocalToLocal
    case cpAllRequiresCopyIn
    case replicaNotFound(service: String, index: Int, project: String)
    case invalidMachineName(String)
    case machineNotFound(String)
    case machineStopped(String, reason: MachineStoppedReason)
    case machineNotRunning(String)
    case machineBootFailed(String, underlying: Error)
    case machineUnsupportedCommand(String)
    case machineUnsupportedOperation(String)
    case machineCommandFailed(machine: String, command: String, exitCode: Int32)
}
